"""shop image captions

Revision ID: 1e2d680edb86
Revises: 80e186e7c2f8
Create Date: 2026-09-24 23:51:14.939430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2d680edb86'
down_revision: Union[str, None] = '80e186e7c2f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_images', sa.Column('caption', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_images', 'caption')
    # ### end Alembic commands ###
