"""shop description and banner images

Revision ID: 93758a9bf80f
Revises: 6e4a3a53ae33
Create Date: 2026-09-24 23:07:38.603590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93758a9bf80f'
down_revision: Union[str, None] = '6e4a3a53ae33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_images_shop_id'), 'shop_images', ['shop_id'], unique=False)
    op.add_column('shops', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'description')
    op.drop_index(op.f('ix_shop_images_shop_id'), table_name='shop_images')
    op.drop_table('shop_images')
    # ### end Alembic commands ###
