"""market asks

Revision ID: e8eac9f98cfe
Revises: 1e2d680edb86
Create Date: 2026-09-25 00:41:01.773186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8eac9f98cfe'
down_revision: Union[str, None] = '1e2d680edb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_asks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_user_id', sa.Integer(), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_asks_customer_user_id'), 'market_asks', ['customer_user_id'], unique=False)
    op.create_index(op.f('ix_market_asks_pincode'), 'market_asks', ['pincode'], unique=False)
    op.add_column('product_requests', sa.Column('ask_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_product_requests_ask_id'), 'product_requests', ['ask_id'], unique=False)
    op.create_foreign_key(None, 'product_requests', 'market_asks', ['ask_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_requests', type_='foreignkey')
    op.drop_index(op.f('ix_product_requests_ask_id'), table_name='product_requests')
    op.drop_column('product_requests', 'ask_id')
    op.drop_index(op.f('ix_market_asks_pincode'), table_name='market_asks')
    op.drop_index(op.f('ix_market_asks_customer_user_id'), table_name='market_asks')
    op.drop_table('market_asks')
    # ### end Alembic commands ###
